name: dart_nats
description: A Dart client for the NATS messaging system. Design to use with Dart and flutter.
version: 1.0.0
homepage: https://github.com/chartchuo
repository: https://github.com/chartchuo/dart-nats

environment:
  sdk: '>=3.0.0 <4.0.0'

# dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.0
  # pedantic: ^1.11.0
dependencies: 
  base32: 2.1.3
  # cryptography: ^2.0.5
  ed25519_edwards: 0.3.1
  mutex: 3.0.0
  web_socket_channel: 2.4.0
